name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:
    name: 'Build and test job'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]    
    steps:
      - name: 'Checkout the code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Validate Build'
        run: |
          npm install
          npm run build
      
      - name: 'Test Build'
        run: |
          npm test --if-exists
